feature_management:
  agents:
    QuizzBot:
      - user_123
      - user_456
    Feedback Classification:
      - user_789
    PPT to Doc:
      - user_123
      - user_999
    Cheque Inference:
      - user_123
      - user_456
      - user_789
    Reply Engine(GRD):
      - user_123
      - user_456
    Nodal: Meeting Minutes:
      - user_789
      - user_999
    Business Loan CRAN [Sample]:
      - user_123
    CIBIL Analyser [Sample]:
      - user_456
    Quiz Generator!:
      - user_123
      - user_456
      - user_789
    Audio: Meeting Minutes:
      - user_123
      - user_999
    Labels Scanner [Sample]:
      - user_456
      - user_789
    Marketing Pitch [Sample]:
      - user_123
      - user_999
    Compliance:
      - user_456
      - user_789
    Stocks_statements_Agri:
      - user_123
      - user_456
    Stocks_statements_Consumer:
      - user_789
      - user_999
    Reply Engine V2 [Experimental]:
      - user_123
    Compliance Checklist V2 [Experimental]:
      - user_456
